/* DIAMONDCLAW - self-contained Arc Mainnet frontend */
const CONFIG = {
  chainId: '0x13b2', chainIdDecimal: 5042, chainName: 'Arc Mainnet',
  nativeCurrency: { name: 'USD Coin', symbol: 'USDC', decimals: 18 },
  rpcUrls: ['https://rpc.mainnet.arc.io'], blockExplorerUrls: ['https://explorer.arc.io'],
  token: '0x412bC8cee1F7F31818fA76c91B754F0CE5496501',
  usdc: '0x3600000000000000000000000000000000000000',
  dexes: [
    {name:'AchSwap V2', factory:'0xb0C2B0acb9c13079dDd871eDaF43Aabf6e88C530', router:'0x52FE40c00530db2e43d01652f903870571A14AFD', url:'https://trade.achswap.app/'},
    {name:'Uniswap V2', factory:'0x89e5DB8B5aA49aA85AC63f691524311AEB649eba', router:'0x1f7d7550B1b028f7571E69A784071F0205FD2EfA', url:'https://app.uniswap.org/'}
  ],
  slippageBps: 1000
};
const ERC20_ABI = [
 {constant:true,inputs:[{name:'owner',type:'address'}],name:'balanceOf',outputs:[{name:'',type:'uint256'}],payable:false,stateMutability:'view',type:'function'},
 {constant:true,inputs:[],name:'decimals',outputs:[{name:'',type:'uint8'}],payable:false,stateMutability:'view',type:'function'},
 {constant:true,inputs:[],name:'symbol',outputs:[{name:'',type:'string'}],payable:false,stateMutability:'view',type:'function'},
 {constant:true,inputs:[],name:'name',outputs:[{name:'',type:'string'}],payable:false,stateMutability:'view',type:'function'},
 {constant:true,inputs:[],name:'totalSupply',outputs:[{name:'',type:'uint256'}],payable:false,stateMutability:'view',type:'function'},
 {constant:true,inputs:[{name:'owner',type:'address'},{name:'spender',type:'address'}],name:'allowance',outputs:[{name:'',type:'uint256'}],payable:false,stateMutability:'view',type:'function'},
 {constant:false,inputs:[{name:'spender',type:'address'},{name:'amount',type:'uint256'}],name:'approve',outputs:[{name:'',type:'bool'}],payable:false,stateMutability:'nonpayable',type:'function'}
];
const FACTORY_ABI = [
 {constant:true,inputs:[{name:'tokenA',type:'address'},{name:'tokenB',type:'address'}],name:'getPair',outputs:[{name:'pair',type:'address'}],payable:false,stateMutability:'view',type:'function'}
];
const ROUTER_ABI = [
 {constant:true,inputs:[{name:'amountIn',type:'uint256'},{name:'path',type:'address[]'}],name:'getAmountsOut',outputs:[{name:'amounts',type:'uint256[]'}],payable:false,stateMutability:'view',type:'function'},
 {constant:false,inputs:[{name:'amountIn',type:'uint256'},{name:'amountOutMin',type:'uint256'},{name:'path',type:'address[]'},{name:'to',type:'address'},{name:'deadline',type:'uint256'}],name:'swapExactTokensForTokens',outputs:[{name:'amounts',type:'uint256[]'}],payable:false,stateMutability:'nonpayable',type:'function'},
 {constant:false,inputs:[{name:'amountIn',type:'uint256'},{name:'amountOutMin',type:'uint256'},{name:'path',type:'address[]'},{name:'to',type:'address'},{name:'deadline',type:'uint256'}],name:'swapExactTokensForTokensSupportingFeeOnTransferTokens',outputs:[],payable:false,stateMutability:'nonpayable',type:'function'}
];
let web3=null, account=null, token=null, usdc=null, tokenDecimals=18, tokenSymbol='CLAW', tokenName='DiamondClaw', activeDex=null, pair=null;
const $=id=>document.getElementById(id);
const all=s=>Array.from(document.querySelectorAll(s));
function msg(text,ok=false){let el=$('actionMessage');if(!el){el=document.createElement('div');el.id='actionMessage';el.className='action-message';document.body.appendChild(el)}el.textContent=text;el.classList.toggle('success',ok);el.classList.add('show');clearTimeout(window._msg);window._msg=setTimeout(()=>el.classList.remove('show'),7000)}
function short(a){return a?`${a.slice(0,6)}...${a.slice(-4)}`:'Connect Wallet'}
function isZero(a){return !a||/^0x0{40}$/i.test(a)}
function units(v,d){const s=String(v).trim();if(!/^\d+(\.\d+)?$/.test(s))throw Error('Geçersiz miktar');let [w,f='']=s.split('.');f=(f+'0'.repeat(d)).slice(0,d);return web3.utils.toBN(w).mul(web3.utils.toBN(10).pow(web3.utils.toBN(d))).add(web3.utils.toBN(f||'0'))}
function fmtRaw(raw,d,max=6){try{const bn=web3.utils.toBN(String(raw)),base=web3.utils.toBN(10).pow(web3.utils.toBN(d));const w=bn.div(base).toString();const f=bn.mod(base).toString().padStart(d,'0').replace(/0+$/,'');return Number(f?`${w}.${f}`:w).toLocaleString('en-US',{maximumFractionDigits:max})}catch{return '0'}}
function set(id,v){if($(id))$(id).textContent=v}
function ensureWeb3(){if(window.Web3){web3=web3||new Web3(window.ethereum||CONFIG.rpcUrls[0]);return Promise.resolve()}return new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/web3@1.10.0/dist/web3.min.js';s.onload=()=>{web3=new Web3(window.ethereum||CONFIG.rpcUrls[0]);res()};s.onerror=()=>rej(Error('Web3 yüklenemedi'));document.head.appendChild(s)})}
function initContracts(){token=new web3.eth.Contract(ERC20_ABI,CONFIG.token);usdc=new web3.eth.Contract(ERC20_ABI,CONFIG.usdc)}
async function metadata(){if(!token)return;try{tokenSymbol=await token.methods.symbol().call()}catch{}try{tokenName=await token.methods.name().call()}catch{}try{tokenDecimals=Number(await token.methods.decimals().call())}catch{}all('[data-token-symbol]').forEach(e=>e.textContent=tokenSymbol);all('[data-ca]').forEach(e=>e.textContent=CONFIG.token);set('totalSupplyValue',await token.methods.totalSupply().call().then(x=>fmtRaw(x,tokenDecimals,2)).catch(()=> 'On-chain'))}
function walletModal(){if($('walletModal'))return;const m=document.createElement('div');m.id='walletModal';m.className='wallet-modal';m.innerHTML=`<div class="wallet-modal-card"><button class="wallet-close" aria-label="Close">×</button><div class="wallet-modal-icon">💎🐾</div><h2>Connect Wallet</h2><p>Connect MetaMask to Arc Mainnet.</p><button class="wallet-option" id="metamaskConnect">🦊 <strong>MetaMask</strong></button><div class="wallet-network-note">Arc Mainnet · Chain ID 5042 · Gas: USDC</div><div id="walletError" class="wallet-error" hidden></div></div>`;document.body.appendChild(m);m.querySelector('.wallet-close').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};m.querySelector('#metamaskConnect').onclick=connect}
function openWallet(){walletModal();$('walletModal').classList.add('open')}
function bindWalletButtons(){all('#connectWallet,#walletBtn,[data-connect-wallet]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound=1;b.onclick=e=>{e.preventDefault();account?disconnect():openWallet()}})}
async function connect(){if(!window.ethereum){walletModal();$('walletError').hidden=false;$('walletError').textContent='MetaMask bulunamadı.';return}try{await ensureWeb3();await window.ethereum.request({method:'eth_requestAccounts'});await switchNetwork();account=(await window.ethereum.request({method:'eth_accounts'}))[0];web3=new Web3(window.ethereum);initContracts();await metadata();updateWallet();await loadData();$('walletModal')?.classList.remove('open');msg(`Bağlandı: ${short(account)}`,true)}catch(e){console.error(e);walletModal();$('walletError').hidden=false;$('walletError').textContent=e.message||'Wallet bağlantısı başarısız.'}}
async function switchNetwork(){const cid=await window.ethereum.request({method:'eth_chainId'});if(cid.toLowerCase()===CONFIG.chainId)return;try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:CONFIG.chainId}]})}catch(e){if(e.code===4902)await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:CONFIG.chainId,chainName:CONFIG.chainName,nativeCurrency:CONFIG.nativeCurrency,rpcUrls:CONFIG.rpcUrls,blockExplorerUrls:CONFIG.blockExplorerUrls}]});else throw Error('MetaMask içinde Arc Mainnet (5042) seçimini onaylayın.')}}
function updateWallet(){all('#connectWallet,#walletBtn').forEach(b=>{b.innerHTML=account?`<i class="fas fa-wallet"></i> ${short(account)}`:`<i class="fas fa-wallet"></i> Connect Wallet`;b.classList.toggle('connected',!!account)});set('connectedWallet',account?short(account):'Not connected')}
function disconnect(){account=null;activeDex=null;pair=null;updateWallet();updateGate();msg('Wallet disconnected')}
function updateGate(){const gate=$('notConnected'),content=$('dashboardContent');if(gate)gate.style.display=account?'none':'block';if(content)content.style.display=account?'block':'none';const sg=$('notConnectedStake'),sc=$('stakeContent');if(sg)sg.style.display=account?'none':'block';if(sc)sc.style.display=account?'block':'none'}
async function bal(c,addr,d){return fmtRaw(await c.methods.balanceOf(addr).call(),d)}
async function loadData(){if(!account||!token)return;updateGate();try{const [claw,usdcBal]=await Promise.all([token.methods.balanceOf(account).call(),usdc.methods.balanceOf(account).call()]);const clawN=Number(web3.utils.fromWei(claw,'ether'))*(tokenDecimals===18?1:Math.pow(10,18-tokenDecimals));set('clawBalance',fmtRaw(claw,tokenDecimals,2)+' '+tokenSymbol);set('availableBalance',fmtRaw(claw,tokenDecimals,4)+' '+tokenSymbol);set('fromBalance','Balance: '+fmtRaw(usdcBal,6,2)+' USDC');set('toBalance','Balance: '+fmtRaw(claw,tokenDecimals,4)+' '+tokenSymbol);set('gripStrength',fmtRaw(claw,tokenDecimals,2));set('stakedAmount','Not configured');set('pendingRewards','Not configured');set('stakedValue','—');set('rewardsValue','—');set('totalEarned','—');set('currentTier',tierFor(Number(fmtRaw(claw,tokenDecimals,6).replace(/,/g,''))).name);set('nextTier',nextTier(Number(fmtRaw(claw,tokenDecimals,6).replace(/,/g,''))));}catch(e){console.error(e)}await discoverPair();await updateQuote()}
function tierFor(n){const tiers=[['Baby Claw',1000],['Iron Claw',10000],['Steel Claw',50000],['Titanium Claw',250000],['Diamond Claw',1000000],['Alpha Claw',5000000]];let t=tiers[0];for(const x of tiers)if(n>=x[1])t=x;return{name:t[0],min:t[1]}}
function nextTier(n){const tiers=[['Iron Claw',10000],['Steel Claw',50000],['Titanium Claw',250000],['Diamond Claw',1000000],['Alpha Claw',5000000]];return tiers.find(x=>n<x[1])?.[0]||'Max Tier'}
async function discoverPair(){if(!web3)return null;pair=null;activeDex=null;for(const d of CONFIG.dexes){try{const f=new web3.eth.Contract(FACTORY_ABI,d.factory);const p=await f.methods.getPair(CONFIG.usdc,CONFIG.token).call();if(!isZero(p)){pair=p;activeDex=d;break}}catch(e){}}set('pairAddress',pair?pair:'No live V2 pair found');set('pairStatus',pair?`${activeDex.name} · Live pair detected`:'No live USDC/CLAW V2 pair detected');return pair}
function tradeState(){const f=$('fromToken')?.dataset.symbol||'USDC',t=$('toToken')?.dataset.symbol||tokenSymbol;return{from:f,to:t,fromAddr:f==='USDC'?CONFIG.usdc:CONFIG.token,toAddr:t==='USDC'?CONFIG.usdc:CONFIG.token,fromDec:f==='USDC'?6:tokenDecimals,toDec:t==='USDC'?6:tokenDecimals}}
function setToken(side,sym){const b=$(side==='from'?'fromToken':'toToken');if(!b)return;b.dataset.symbol=sym;b.querySelector('[data-symbol]').textContent=sym;b.querySelector('[data-token-icon]').textContent=sym==='USDC'?'$':'🐾';updateQuote()}
function tokenMenu(side){const b=$(side==='from'?'fromToken':'toToken');if(!b)return;document.querySelectorAll('.token-menu').forEach(x=>x.remove());const m=document.createElement('div');m.className='token-menu';['USDC',tokenSymbol].forEach(s=>{const x=document.createElement('button');x.textContent=s;x.onclick=()=>{setToken(side,s);m.remove()};m.appendChild(x)});b.parentElement.appendChild(m)}
async function updateQuote(){const i=$('fromAmount'),o=$('toAmount');if(!i||!o)return;const st=tradeState();const amount=String(i.value||'').trim();if(!amount||Number(amount)<=0||st.from===st.to){o.value='';return}if(!pair||!activeDex){o.value='';set('liveRate','No route');set('pairStatus','No live V2 liquidity found');return}try{const r=new web3.eth.Contract(ROUTER_ABI,activeDex.router);const raw=units(amount,st.fromDec);const arr=await r.methods.getAmountsOut(raw.toString(),[st.fromAddr,st.toAddr]).call();o.value=fmtRaw(arr[1],st.toDec,8).replace(/,/g,'');set('liveRate',`1 ${st.from} ≈ ${fmtRaw(arr[1],st.toDec,8)}`);set('pairStatus',`${activeDex.name} · Live quote · 10% slippage max`)}catch(e){o.value='';set('liveRate','No live quote');set('pairStatus','Pair exists but quote unavailable for this amount')}}
async function executeSwap(){if(!account)return openWallet();if(!pair||!activeDex){await discoverPair();if(!pair)return msg('Bu CLAW için Arc Mainnet üzerinde V2 likidite çifti bulunamadı. Önce likidite oluşturulmalı.')}const st=tradeState(),value=String($('fromAmount')?.value||'').trim();if(!value||Number(value)<=0)return msg('Swap miktarı girin.');try{const raw=units(value,st.fromDec),r=new web3.eth.Contract(ROUTER_ABI,activeDex.router),sell=st.from==='USDC'?usdc:token;const allowance=await sell.methods.allowance(account,activeDex.router).call();if(web3.utils.toBN(allowance).lt(raw)){msg(`Approve ${st.from}: MetaMask işlemini onaylayın...`);await sell.methods.approve(activeDex.router,raw.toString()).send({from:account});}const arr=await r.methods.getAmountsOut(raw.toString(),[st.fromAddr,st.toAddr]).call();const quoted=web3.utils.toBN(arr[1]);const minOut=quoted.mul(web3.utils.toBN(10000-CONFIG.slippageBps)).div(web3.utils.toBN(10000));const deadline=Math.floor(Date.now()/1000)+1200;msg('Swap için MetaMask onayını bekliyor...');await r.methods.swapExactTokensForTokensSupportingFeeOnTransferTokens(raw.toString(),minOut.toString(),[st.fromAddr,st.toAddr],account,deadline).send({from:account});msg('Swap başarıyla gönderildi. Explorer üzerinden kontrol edebilirsiniz.',true);await loadData();updateQuote()}catch(e){console.error(e);msg(e?.message||'Swap başarısız.')}}
function setupTrade(){const f=$('fromToken'),t=$('toToken');if(f)f.onclick=()=>tokenMenu('from');if(t)t.onclick=()=>tokenMenu('to');const sw=$('switchTokens');if(sw)sw.onclick=()=>{const a=f.dataset.symbol||'USDC',b=t.dataset.symbol||tokenSymbol;setToken('from',b);setToken('to',a)};$('fromAmount')?.addEventListener('input',updateQuote);$('swapBtn')?.addEventListener('click',executeSwap);$('maxBtn')?.addEventListener('click',async()=>{if(!account)return openWallet();const st=tradeState();const c=st.from==='USDC'?usdc:token;const d=st.from==='USDC'?6:tokenDecimals;const raw=await c.methods.balanceOf(account).call();$('fromAmount').value=fmtRaw(raw,d,8).replace(/,/g,'');updateQuote()});updateQuote()}
function setupUtilities(){all('[data-copy-ca]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(CONFIG.token);msg('CA copied',true)}catch{msg(CONFIG.token)}});all('[data-explorer]').forEach(a=>a.href=`https://explorer.arc.io/address/${CONFIG.token}`);all('[data-add-token]').forEach(b=>b.onclick=async()=>{if(!window.ethereum)return openWallet();try{await window.ethereum.request({method:'wallet_watchAsset',params:[{type:'ERC20',options:{address:CONFIG.token,symbol:tokenSymbol,decimals:tokenDecimals}}]})}catch(e){msg(e.message||'Token eklenemedi')}})}
function setupRewards(){const b=$('claimRewardsBtn');if(b)b.onclick=()=>{if(!account)return openWallet();msg('Claim contract is not configured. Token CA tek başına claim fonksiyonu sağlamaz.')}}
function setupStake(){const b=$('stakeBtn');if(b)b.onclick=()=>{if(!account)return openWallet();msg('Staking contract is not configured. Token CA tek başına stake fonksiyonu sağlamaz.')};all('.lock-btn').forEach(x=>x.onclick=()=>{all('.lock-btn').forEach(y=>y.classList.remove('active'));x.classList.add('active')})}
async function init(){walletModal();bindWalletButtons();setupUtilities();setupTrade();setupRewards();setupStake();updateGate();await ensureWeb3();web3=new Web3(window.ethereum||CONFIG.rpcUrls[0]);initContracts();await metadata();await discoverPair();const accounts=window.ethereum?await window.ethereum.request({method:'eth_accounts'}):[];if(accounts.length){account=accounts[0];try{const cid=await window.ethereum.request({method:'eth_chainId'});if(cid.toLowerCase()===CONFIG.chainId){web3=new Web3(window.ethereum);initContracts();await metadata();updateWallet();await loadData()}}catch{}}if(window.ethereum&&!window.ethereum.__diamondClawBound){window.ethereum.__diamondClawBound=true;window.ethereum.on('accountsChanged',async a=>{account=a[0]||null;updateWallet();if(account)await loadData();else updateGate()});window.ethereum.on('chainChanged',()=>location.reload())}}
window.DiamondClaw={CONFIG,connect,disconnect,getAccount:()=>account};window.connectWallet=connect;window.addEventListener('DOMContentLoaded',init);
